#!/usr/bin/env bash
hyprctl output create headless sunshine
WIDTH=${SUNSHINE_CLIENT_WIDTH:-2560}
HEIGHT=${SUNSHINE_CLIENT_HEIGHT:-1440}
REFRESH=${SUNSHINE_CLIENT_FPS:-60}
hyprctl keyword monitor "HEADLESS-2,${WIDTH}x${HEIGHT}@${REFRESH},auto,1"